---Drop  RENTALVIDEO Table
DROP TABLE RENTALVIDEO;

---Drop VIDEO Table
DROP TABLE VIDEO;

---Drop RENTALCODE Table
DROP TABLE RENTALCODE;

---Drop RENTAL Table
DROP TABLE RENTAL;

---Drop MEMBERS Table
DROP TABLE MEMBERS;

---Drop BRANCH Table
DROP TABLE BRANCH;

---Drop CATALOG Table
DROP TABLE CATALOG;

---Drop STAFF Table
DROP TABLE STAFF;


-- Create STAFF table
CREATE TABLE STAFF(
STF_ID VARCHAR2(15) CONSTRAINT STF_ID_PK PRIMARY KEY,
STF_FNAME VARCHAR2(20),
STF_LNAME VARCHAR2(20),
STF_ADDRESS VARCHAR2(20),
STF_CITY VARCHAR2(25),
STF_STATE CHAR(2),
STF_ZIP NUMBER(5),
STF_PHONE NUMBER (10),
STF_POSITION VARCHAR2 (10),
STF_SALARY NUMBER (5));

-- Create CATALOG Table
CREATE TABLE CATALOG(
CAT_ID NUMBER(6) CONSTRAINT CAT_ID_PK PRIMARY KEY,
CAT_CATEGORY VARCHAR2(15),
CAT_VIDEOTITLE VARCHAR2(20),
CAT_MAINACTOR VARCHAR2(20),
CAT_DIRECTOR VARCHAR2(20));

-- Create BRANCH Table
CREATE TABLE BRANCH(
BRN_ID NUMBER(5) CONSTRAINT BRN_ID_PK PRIMARY KEY,
BRN_ADDRESS VARCHAR2(20),
BRN_CITY VARCHAR2(20),
BRN_STATE CHAR(2),
BRN_ZIP NUMBER(5),
BRN_AREA NUMBER(3),
BRN_PHONE NUMBER(7),
BRN_MANAGER_ID VARCHAR2(10) CONSTRAINT BRN_MANGER_ID_FK REFERENCES STAFF(STF_ID));

-- Create MEMBERS Table
CREATE TABLE MEMBERS(
MEM_ID VARCHAR2(10) CONSTRAINT MEM_ID_PK PRIMARY KEY,
MEM_FNAME VARCHAR2(15),
MEM_LNAME VARCHAR2(15),
MEM_ADDRESS VARCHAR2(20),
MEM_CITY VARCHAR2(20),
MEM_STATE CHAR(2),
MEM_ZIP NUMBER(5),
MEM_PHONE NUMBER(10),
MEM_DATEOFREGISTER DATE,
MEM_BALANCE NUMBER(6,2));

-- Create RENTAL Table
CREATE TABLE RENTAL(
RNT_ID VARCHAR2(10) CONSTRAINT RNT_ID_PK PRIMARY KEY,
MEM_ID VARCHAR2(10) CONSTRAINT MEM_ID_FK REFERENCES MEMBERS(MEM_ID),
RNT_DATE DATE ,
RNT_TOTALAMT NUMBER(10,2));


-- Create RENTALCODE Table
CREATE TABLE RENTALCODE(
RNT_CODE VARCHAR2(3) CONSTRAINT RNT_CODE_PK PRIMARY KEY,
RNT_CODE_DESCRIPTION VARCHAR2(30),
RNT_CODE_RENTALCOST NUMBER(5, 2));

-- Create VIDEO Table
CREATE TABLE VIDEO(
VDO_ID VARCHAR2 (5) CONSTRAINT VDO_ID_PK PRIMARY KEY,
VDO_STATUS NUMBER(1),
BRN_ID NUMBER(5) CONSTRAINT BRN_ID_FK REFERENCES BRANCH(BRN_ID),
VDO_COST NUMBER(5, 2),
CAT_ID NUMBER(6) CONSTRAINT CAT_ID_FK REFERENCES CATALOG(CAT_ID),
RNT_CODE VARCHAR2(3) CONSTRAINT RNT_CODE_FK REFERENCES RENTALCODE(RNT_CODE));

-- Create RENTALVIDEO Table
CREATE TABLE RENTALVIDEO(
VDO_ID VARCHAR2(5),
RNT_ID VARCHAR2(10),
RNT_VDO_DUEDATE date,
RNT_VDO_RETURNDATE DATE,
CONSTRAINT RNT_VDO_PK PRIMARY KEY (VDO_ID, RNT_ID), 
CONSTRAINT RNT_VDO_FK1 FOREIGN KEY (VDO_ID) REFERENCES VIDEO(VDO_ID),
CONSTRAINT RNT_VDO_FK2 FOREIGN KEY (RNT_ID) REFERENCES RENTAL(RNT_ID));

